### PR TITLE
Add sensitivity functions to produce vector of new pars that vary sd without changing mean

### PR DESCRIPTION
**Pull request by nehill197**
References issue #59

### CODE REVIEW

**Comment by nehill197** [comment]
extras is dependent on the `sn` package, which in turn is dependent on the `Matrix` package, which now requires R >= 4.4.0 (though the actions passed on R 4.3.0). I changed the R dependency to 4.3.0, and updated the R-CMD-check actions from the "overkill" set that included the windows on R 4.1 and the older ubuntu versions to the "check standard" version.

**Comment by nehill197** [comment]
The binomial family of distributions don't seem to have a clear solution to adjust the parameters to expand the sd.
I also haven't included a function for the zero-inflated Poisson distribution because it's proving difficult.

**Comment by nehill197** [comment]
This pull request also includes a handful of styler and lintr suggestions to some of the other functions/tests/vignettes.

**Review by joethorley — APPROVED** [review]
looks great!

**Pull request merged**
